### ISSUE TITLE
Add Chromecast support 

### ISSUE THREAD

**Issue by borntobegeek** [inickt/LazyMan-iOS#33]
I love the app, but I can only watch on my iPhone / iPad because I don't have an Apple TV. Chromecast support would solve this problem for a lot of people.

**Comment by inickt** [comment]
I don't have a Chromecast to test on but I can start looking into this.

**Comment by psyc-ology** [comment]
Any movement on Chromecast support? LOVE the app!

**Comment by inickt** [comment]
@psyc-ology I briefly looked at it a couple months ago and while it might be possible it isn’t something I am able to do and invest the time into right now. That being said I looked again and saw something that I didn’t notice before, so it might be technically possible.

It’s going to be a long time until I could get around to it and I’ll have to get a Chromecast to test but I’ll let you know.

**Comment by psyc-ology** [comment]
Thanks for the quick response! You're awesome!!!

**Comment by olivehalle** [comment]
Merci pour votre apps! Formidable!

**Comment by Alexsays** [comment]
If you want, I have experience with Chromecast development and I'm an iOS developer, so I can take a look in my free time.
I'm currently using the app and it could be nice to have the feature for me too.

**Comment by inickt** [comment]
I just got a Chromecast recently, and started looking at the CAF apps so it is on my radar.

**Comment by Alexsays** [comment]
Perfect! Just let me know if you need some help 👍

**Comment by inickt** [comment]
Hey all– Chromecast support is now out. Sorry this took so long, but try it out and let me know what you think!

@borntobegeek @Alexsays @olivehalle @psyc-ology
