### ISSUE TITLE
Crashes on launch on iOS 12

### ISSUE THREAD

**Issue by inickt** [inickt/LazyMan-iOS#36]

**Comment by inickt** [comment]
Unconfirmed– works in simulator

**Comment by Mattrak** [comment]
I installed the Official release of iOS 12 today, it crashes on launch

**Comment by Mattrak** [comment]
Someone on reddit says that It actually works if we build it ourself with the latest Xcode

**Comment by Mattrak** [comment]
I've just installed LazyMan with the latest version of Cydia Impactor (0.9.47) and I can confirm it is working.

**Comment by inickt** [comment]
Great. Looks like it was an Impactor issue. Going to close but feel free to open issues if you have any iOS 12 bugs.
