### ISSUE TITLE
Yo, make it at least iOS 8 compatible!

### ISSUE THREAD

**Issue by refriedfood** [inickt/LazyMan-iOS#40]
What's going on here. Not everyone uses the new shit iOS, and they're tweaked the fuck out. Why isn't compatibility in xcode supported for iOS8, it uses the same framework that you're using, please add its support.

**Comment by inickt** [comment]
First off, please relax with the language. I am pretty flexible with requests but directly attacking someone usually isn't the best way to ask for something.

If I could have lowered the iOS requirement easily than I would have. You are correct that Xcode does support iOS 8, however some of the libraries and methods I use do not. Less than 1% of active devices currently are running iOS, and for a side project it did not make sense for me to invest the time into that market. Also, all devices that are currently running iOS 8 could update to 9.

It is pretty standard to think most people are not using an operating system that is 4 years old at this point. I did take a look, and some work would need to be done, but it wouldn't be easy to support iOS 8. If you could give me a solid rationale for why this needs to be done, an apology, and maybe contribute a donation to make it worth my time I may reconsider.

**Comment by refriedfood** [comment]
Who's attacking what? What are you talking about? Never come to NY, you'll have a heart attack if you think that was attacking someone. In fact, I'd stay inside all together if you want to tell people how they can talk. But, that's besides the point.

What are you talking about market for? The libraries and methods you use aren't needed for what the application allows. It's dead weight at the moment unless you're, for some reason, radically overhauling the interface when it doesn't need overhauling - that's called trying to reinvent the wheel when all people care about is moving (playing the game). The grabbing methods to your own ran server and masking isn't exactly hidden to someone who knows 101 of programming, and none of the libraries you use are going to change your method of extraction. You could use iOS 4.

Buy hey, If you don't want to do it, fine, you don't. Fuck it, no big deal - let's assume everyone uses the same shit everyone else does and to hell with compatibility. Do what you want. It makes you, not me. It's easier to route your net/java LZ windows app into m3u8 and into any device that has a browser. So, don't let me help you be nice.

And yes, you can read that in whatever twisted fucked up tone which you read the first post in. Maybe its your angry voice, _grrr_.

**Comment by matthewschanzlin** [comment]
refriedfood if it would be ooooh so easy, how about you do it? This guy was nice enough to release this source for free. I hope you are trolling because otherwise I'm very confused as to how entitled you could be to someone else's time.

**Comment by refriedfood** [comment]
It's a request, Matthew. If he doesn't want to do it, then he doesn't have to. And your implications that I'm entitled to his time is fucking absurd and immature. 

And yeah, maybe I will do it.
