### ISSUE TITLE
ios 10.2.1 sideloader and jailbroken returns error

### ISSUE THREAD

**Issue by refriedfood** [inickt/LazyMan-iOS#44]
"iDevice hasn't installed jailbreak patch "AppSync" even though it is installed: https://images2.imgbox.com/5c/99/2Nw8uAlk_o.png

Impactor 0.9.47 crashes on libswiftCore: https://images2.imgbox.com/d3/78/rl7Ahbp9_o.png

version 1.0.1

**Comment by inickt** [comment]
Are you using the latest version of Cydia Impactor? 

If you are Jailbroken you can just download the .ipa and directly install on your device if you have AppSync.

**Comment by inickt** [comment]
I haven’t used either of those tools before so I can’t quite help you there. 

If you have AppSync and Filza installed you should be able to download the .ipa straight from the releases tab here on GitHub, open it in Filza, and install.

**Comment by refriedfood** [comment]
Filza doesn't work either. 3uTools is simply a windows program, like impactor, however 3utools is an all-in-one utilizer for jailbreaking or no jailbroken devices which you can install any ipa, like AppCake via ftp, etc. 

https://images2.imgbox.com/f9/b2/fkd0qQo4_o.png
https://images2.imgbox.com/3b/d0/s14dV7cF_o.png
https://images2.imgbox.com/9c/34/Fk0whBPQ_o.png
https://images2.imgbox.com/4c/ed/1JrFGAXU_o.png

If you have a command line you like me to test it with let me know. I'm aware 10.2.1 isn't the most used iOS, but it's the only one I can test on.

**Comment by inickt** [comment]
I honestly have no clue. You can install from [TweakBox](https://www.tweakboxapp.com/) but it will have ads (that I didn't add). Otherwise I don't really have any ideas. Maybe ask /r/jailbreak? Can you install other .ipas like that?

**Comment by refriedfood** [comment]
I literally just got it to work. I got rid of Appsync Unified and anything relating to it, i.e. appcake, installers, and installed Appsync Unified again and it seemed to have installed via ipa no problem. On a side note, I tried sideloading it onto an 8S, iOS 12.0. It worked for 2 days and then stopped.

**Comment by inickt** [comment]
Hmm thats weird for the 8. Did you reinstall since then?

**Comment by refriedfood** [comment]
Unfortunately no, it was a semi-gift thing I did for a friend when he was in town. I don't have access to his phone and he isn't technically inclined so to speak.

**Comment by inickt** [comment]
Yeah I have a couple people I’ve set it up for but unfortunately with the restrictions Apple places on 3rd party apps not in the App Store it’s not really a set and forgot thing.

**Comment by inickt** [comment]
If you don't have anything else right now I am going to close this issue. Feel free to reply or open up another one if you run into anything else though.
