### ISSUE TITLE
Install fails on iPhone 6s Plus, iOS 12.2 not jailbroken

### ISSUE THREAD

**Issue by AwesomeAL** [inickt/LazyMan-iOS#52]
While trying to install LazyMan.ipa v1.0 using Cydia impactor 0.9.5.1  I get the following error.

![lazyman install error](https://user-images.githubusercontent.com/42872637/56624597-ddb05280-6639-11e9-9f8a-8d66dbc55e1c.png)

**Comment by inickt** [comment]
Hmmm thats weird. I don't add the Network Extensions entitlement anywhere. Can you try 1.1 for me?
https://github.com/inickt/LazyMan-iOS/releases/download/v1.1.0-beta/LazyMan-iOS_1.1.0-606.ipa

**Comment by AwesomeAL** [comment]
Hi, using 1.1 I get the following error:
![lazyman install-Error](https://user-images.githubusercontent.com/42872637/56698819-8078d780-66f3-11e9-8191-c0dccf6cdd45.png)

**Comment by AwesomeAL** [comment]
Hi, using LazyMan-iOS_1.0.1-300.ipa I get the same error now:

![lazyman install-Error-1 0 1](https://user-images.githubusercontent.com/42872637/56699334-5c1dfa80-66f5-11e9-9012-455c59741336.png)

**Comment by AwesomeAL** [comment]
That fixed it, it also might be handy to add the solution in the FAQ or install guide for IOS on reddit as well.
I installed the LazyMan-iOS_1.0.1-300.ipa without any errors after removing the certificates as the link described.

**Comment by inickt** [comment]
Yeah maybe, but its a general Cydia Impactor problem, not the app itself. Glad it worked.
