### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by code-ui** [inickt/LazyMan-iOS#74]
It looks like [r/LazyMan](https://www.reddit.com/r/LazyMan/) is now private, and the [original repo](https://github.com/StevensNJD4/LazyMan) is now giving a 404.

When trying to view a game I'm getting an error about `Could not create master playlist URL`.

What is the status of this project?

**Comment by SubtleHyperbole** [comment]
Was wondering the same

**Comment by inickt** [comment]
Hey @code-ui @ciarabryans @alec42 @SubtleHyperbole. Sorry for the lack of response on this. I am not in control of the servers that provide the streams, and have no interest in running them myself for a number of reasons. /r/LazyMan has shut down and I haven't really talked to the original creator of what the status of the app is. 

If the servers come back up I don't mind maintaining the iOS app but will most likely not develop new feature. Thank you for understanding!

**Comment by abuhamsa** [comment]
Dont you just have to edit this line https://github.com/inickt/LazyMan-iOS/blob/8fdd952ac5c7b0bfbc8c9bb99528873f7c63b1db/LazyManCore/Managers/FeedManager.swift#L129 ?

Change "http://nhl.freegamez.ga" to "http://freegamez.ga"

**Comment by inickt** [comment]
I released [v1.3.0](https://github.com/inickt/LazyMan-iOS/releases/tag/v1.3.0) for the season update.
