### ISSUE TITLE
Is this still live?

### ISSUE THREAD

**Issue by neauxm** [inickt/LazyMan-iOS#80]
I found this when searching for a tvOS solution.

Is this still being maintained and any chance for a tvOS verrsion?

**Comment by inickt** [comment]
I released [v1.3.0](https://github.com/inickt/LazyMan-iOS/releases/tag/v1.3.0) for the season update.

**Comment by inickt** [comment]
As per tvOS- hopefully in the next one but wanted to get something out before the season started.
