### ISSUE TITLE
iOS App update for new 2021/2022 season?

### ISSUE THREAD

**Issue by blodt** [inickt/LazyMan-iOS#82]
I’m just wondering if anybody knows if there is a chance for an updated iOS app for the upcoming season and addition of the Kraken?

Many thanks in advance!

**Comment by inickt** [comment]
Yeah I am working on it. I will probably split off a 1.3 update before working on rewriting everything: https://github.com/inickt/LazyMan-iOS/pull/81

No ETA but trying to have something out before the season starts.

**Comment by blodt** [comment]
Thank you VERY VERY much!!!

**Comment by Numbski** [comment]
Subscribed.  Wish I could do more to help, but shell scripting, perl scripting, and javascript amounts to basically squat here.  I've intended for years to pick up Swift, but never quite have the time.  :\

**Comment by inickt** [comment]
I released [v1.3.0](https://github.com/inickt/LazyMan-iOS/releases/tag/v1.3.0) for the season update.

**Comment by refriedfood** [comment]
Can't get it to install using extender on a 7+ iOS 11.2.2. v1.2.1 works fine, however, freegamez.ga went down and they use freesports.ddns.net as their proxy ip. No idea what your app is using, but even when changing it in the hosts file to its ip, the games in 1.2.1 no longer resolve (cannot create master playlist url). I don't think your newest version is compatible any longer with my ios.
