### ISSUE TITLE
Casting does not work

### ISSUE THREAD

**Issue by JoshNotWright** [inickt/LazyMan-iOS#85]
iPhone Xr, iOS 15.1. 

When you connect to the chromecast, it shows the Lazyman logo. When you go to select a game, it attempts to load briefly then the feed closes. 
https://user-images.githubusercontent.com/17754256/137206578-398be765-12a5-45e5-b999-bcd2bc548665.MOV

**Comment by inickt** [comment]
That it is. Looks like my hack to get it working got blocked, I will try and figure something out.

**Comment by inickt** [comment]
Theoretically this is fixed but I won't be able to test until later. MLB games should work but NHL may not.

**Comment by inickt** [comment]
Tested, looks like its fine now so lmk if you have any other issues.
