### ISSUE TITLE
Error “Could not create master playlist URL.”

### ISSUE THREAD

**Issue by Galorlx** [inickt/LazyMan-iOS#89]
This happens when ever I try to play an NHL or MLB game for the live version or the full game. But this never happens when I just watch the recaps already on YouTube no madder what version I try. Any help?

**Comment by refriedfood** [comment]
Assuming your device is jail broken, use shell client/terminal client or ftp into your phone, goto /etc/ grab your hosts file and add the following:

```
165.22.201.101 freegamez.ga
165.22.201.101 mf.svc.nhl.com
165.22.201.101 mlb-ws-mf.media.mlb.com
165.22.201.101 media.mlb.com
165.22.201.101 playback.svcs.mlb.com
```

Then over write it on your phone. If it doesn't work, then comment out or remove those lines from your hosts file. the .ga is dead and either the app is calling to it, or it might just be that your game isn't available through the proxy, which happens on occasion. If it is all, then definitely try what I said.

**Comment by Galorlx** [comment]
> Assuming your device is jail broken, use shell client/terminal client or ftp into your phone, goto /etc/ grab your hosts file and add the following:
> 
> ```
> 165.22.201.101 freegamez.ga
> 165.22.201.101 mf.svc.nhl.com
> 165.22.201.101 mlb-ws-mf.media.mlb.com
> 165.22.201.101 media.mlb.com
> 165.22.201.101 playback.svcs.mlb.com
> ```
> 
> Then over write the file on your phone. If it doesn't work, then comment out or remove those lines from your hosts file. the .ga is dead and either the app is calling to it, or it might just be that your game isn't available through the proxy, which happens on occasion. If it is all, then definitely try what I said. **Can't help with mlb at the moment.

I’m not really the smartest person to do that but yes I’m jailbroken and I don’t have a terminal either

**Comment by Galorlx** [comment]
> Assuming your device is jail broken, use shell client/terminal client or ftp into your phone, goto /etc/ grab your hosts file and add the following:
> 
> ```
> 165.22.201.101 freegamez.ga
> 165.22.201.101 mf.svc.nhl.com
> 165.22.201.101 mlb-ws-mf.media.mlb.com
> 165.22.201.101 media.mlb.com
> 165.22.201.101 playback.svcs.mlb.com
> ```
> 
> Then over write the file on your phone. If it doesn't work, then comment out or remove those lines from your hosts file. the .ga is dead and either the app is calling to it, or it might just be that your game isn't available through the proxy, which happens on occasion. If it is all, then definitely try what I said. **Can't help with mlb at the moment.

Here is also a problem when in Filza and installing it I get this error “Rejected downgrade of system/internal app dev.nickt.LazyMan-iOS installed version is 720, proposed version is 720.” So this brings me to think there’s somewhere data of lazy man that’s breaking it right now

**Comment by Galorlx** [comment]
> Assuming your device is jail broken, use shell client/terminal client or ftp into your phone, goto /etc/ grab your hosts file and add the following:
> 
> ```
> 165.22.201.101 freegamez.ga
> 165.22.201.101 mf.svc.nhl.com
> 165.22.201.101 mlb-ws-mf.media.mlb.com
> 165.22.201.101 media.mlb.com
> 165.22.201.101 playback.svcs.mlb.com
> ```
> 
> Then over write the file on your phone. If it doesn't work, then comment out or remove those lines from your hosts file. the .ga is dead and either the app is calling to it, or it might just be that your game isn't available through the proxy, which happens on occasion. If it is all, then definitely try what I said. **Can't help with mlb at the moment.

I have done all of what you said and it didn’t work any more ideas I even tried to batch uninstall but no

**Comment by refriedfood** [comment]
They stream through a proxy to hide the mediaAuth key that is needed to stream. So, reinstalling it isn't going to be the problem unless the program doesn't open on your phone. Right now they're resolving to a proxy domain called: freesports.ddns.net -- so, if you ping that, and change the ips to the correct ones in your hosts file, whenever you use the program it will try to connect to that new ip, which the proxy server is now being hosted on. According to the site they're having resolve issues, so you may not see it work for a day or so.

**Comment by Galorlx** [comment]
> They stream through a proxy to hide the mediaAuth key that is needed to stream. So, reinstalling it isn't going to be the problem unless the program doesn't open on your phone. Right now they're resolving to a proxy domain called: freesports.ddns.net -- so, if you ping that, and change the ips to the correct ones in your hosts file, whenever you use the program it will try to connect to that new ip, which the proxy server is now being hosted on. According to the site they're having resolve issues, so you may not see it work for a day or so.

How would I specifically host it or does it just automatically do it when it’s in the host file? But I get what you mean.

**Comment by inickt** [comment]
The new ddns URL does not have HTTPS/SSL support, so simply changing it in `/etc/hosts` won't work on 1.3. Probably would on 1.2 but it has its own problems. 

Might be the end of maintenance for this project, it's quite the cat and mouse game for running it.

**Comment by Galorlx** [comment]
> The new ddns URL does not have HTTPS/SSL support, so simply changing it in `/etc/hosts` won't work on 1.3. Probably would on 1.2 but it has its own problems.
> 
> Might be the end of maintenance for this project, it's quite the cat and mouse game for running it.

So your saying I can’t fix this essentially

**Comment by refriedfood** [comment]
Maybe I should have mentioned I still use 1.2, if that's the case. 1.3 doesn't even work on my phone in any capacity anyhow, and I don't mind not having a kraken icon...

**Comment by Galorlx** [comment]
> Maybe I should have mentioned I still use 1.2.1, if that's the case. 1.3 doesn't even work on my phone in any capacity anyhow, and I don't mind not having a kraken icon...

So your saying the way you did that it works on 1.2.1 why not for me then? Did I do something wrong?

**Comment by inickt** [comment]
https://github.com/inickt/LazyMan-iOS/releases/tag/v1.3.1
