### ISSUE TITLE
Streams saying “Could not create master playlist url”

### ISSUE THREAD

**Issue by Galorlx** [inickt/LazyMan-iOS#90]
I’ve done everything and the host file stuff ain’t doing anything if you have an in depth way or anything that’s worked in past experience tell it to me but if you wanna go back and forth message me on discord at Loyah#2370 or just any ideas just tell me on discord or here. Thanks for the help!

**Comment by inickt** [comment]
None of the host file changes matter anymore. 
1. What version are you running?
2. What game are you trying to play?

**Comment by Galorlx** [comment]
any game its all the same on all the versions I’ve tried 1.3.0 and 1.2.1

**Comment by inickt** [comment]
Neither of those are supported, please try 1.3.1.

**Comment by Galorlx** [comment]
Oh
