### ISSUE TITLE
Doesn't run on the following since 1.3

### ISSUE THREAD

**Issue by refriedfood** [inickt/LazyMan-iOS#91]
What I mean by not run is: 1.3 will open and immediately shut (even though it is open in the b.g. and inaccesesible), versions below 1.2 open fine but give a could not create master playlist error (regardless if the hosts file points to the right domain/ips).
Phones:
XR ios 13+ -- doesn't run
7 -ios12 -- doesn't run, lower versions run but cannot create
ipad 2 9.3 (highest ios it has) -- doesn't run, lower versions run but cannot create

Not sure the reasons why, as it works on a 7plus running 13.2.2

Let me know if you want to run any test builds on those, and I can help.

**Comment by teemuensio** [comment]
I noticed this problem today
![95F3E90C-542F-4F08-85FD-052DBE232666](https://user-images.githubusercontent.com/96999581/147889814-646e56c6-b2d9-4771-8cc3-27b2d4ddd3ea.png)

**Comment by inickt** [comment]
How are you installing? If through the IPA, how are you getting it on your device? If jailbroken, are you using the deb? Are you using 1.3 or 1.3.1?

**Comment by teemuensio** [comment]
Hi,
LazyMan is was downloaded from Signulous app.

-Teemu

Nick Thompson ***@***.***> kirjoitti 6.1.2022 kello 0.52:

﻿

How are you installing? If through the IPA, how are you getting it on your device? If jailbroken, are you using the deb? Are you using 1.3 or 1.3.1?

**Comment by refriedfood** [comment]
I upload it via ftp directly to a directory on my phone. Then use appinst file.ipa to install it via ssh, like I do for all ipas. I even tried it using sideloadly and it ends with the same result. Installation is always successful, but it does the same thing on both phones, opens the loading LM screen, then kicks you to the springboard. If you check what it running (either by double tapping the button or hold drag) it shows its running, but when you select it, again it just flashes then kicks you out.

With the deb, however, it runs fine on the (XR 13.4.1).

What is weird is the older versions run fine using all install methods, they just don't create master playlists. Do you have a recommended install for the ipa outside of using dpkg?

**Comment by inickt** [comment]
@teemuensio I don't support installations not through the deb or ipa I provide. It seems like your app launches anyways so I'd refer you to #92.

@refriedfood Good news is that the unc0ver jailbreak for 14.8 just came out and I am using my XS as a test device now. I was playing around earlier with some remote app signing things and noticed LazyMan also crashing. I have confirmed:
1. Normal installation using `appinst`/other direct installation methods fail and will crash on launch (normal install for Sideloadly)
2. Installing through Filza or Sideloadly with an Apple ID Sideload or Ad-hoc sign will let the app launch fine.
At this point I think whatever I did between 1.2 and 1.3 broke something with the code signature. I do fakesign the deb so looks like I need to do the same for the ipa if I don't want to include my dev cert. I'll keep investigating and keep you posted!

**Comment by inickt** [comment]
@refriedfood mind testing [this ipa](https://drive.google.com/uc?export=download&id=1MfRJzEEh5H4iWpYb8Xyyz7D5rQ8OnC6o) for me? I think I fixed the signing– I got it working using `appinst` and Sideloadly with normal install, but would like confirmation.

**Comment by refriedfood** [comment]
That did it. I tested via appinst and sideloadly and they both worked. Nice job!

**Comment by inickt** [comment]
Sweet! Thanks for testing. I'll push 1.3.2 sooner than later with the fixes to building. I also think I figured out a 1 click install method as long as you are jailbroken and have AppSync installed.
